Apply StyleCop to project
amzn/ion-object-mapper-dotnet pull request #9
Opened 2021-05-11 18:32 UTC by justing-bq

Apply StyleCop to project

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-05-12 05:05 UTC, kylepbit approved these changes

2021-05-12 16:39 UTC, justing-bq commented on Amazon.Ion.ObjectMapper/IonSerializer.cs
> +    public interface IIonReaderFactory
Pardon me, where is the structural change? This code is just renaming the reader factory.

2021-05-12 16:52 UTC, kylepbit commented on Amazon.Ion.ObjectMapper/IonSerializer.cs
> +    public interface IIonReaderFactory
Sorry - the renaming of IonReaderFactor to IIonReaderFactory - I think StyleCop says interfaces should be prefixed with `I` which is a "structural" change in that it changes class names. Worth calling out explicitly.

2021-05-19 20:24 UTC, alpian requested changes
Not convinced StyleCop is needed. If it is needed it needs to be customized for the deliberate "violations" we need. e.g. public fields that can be internal but are deliberately not.

2021-05-19 20:24 UTC, alpian commented on Amazon.Ion.ObjectMapper.Test/TestObjects.cs
> +        internal readonly string firstName;
StyleCop doesn't realise that these are public for a good reason.

2021-05-21 21:36 UTC, alpian commented
Going to close this one, it will be completely different when we actually make this change.

2021-05-21 21:36 UTC, closed without merging